### ISSUE TITLE
Add a function combining andThen with runCatching

### ISSUE THREAD

**Issue by oddsund** [michaelbull/kotlin-result#54]
Hello,

First of all, sorry for not fixing that typo in the PR i sent you 😅 

A common pattern I see when wrapping library code is the following;
```kotlin
.andThen {
	runCatching {
		// lib code
	}
}
```

The following creates an annoying typewarning, and looks wonky;
```kotlin
.map {
   // code
}.runCatching {
	if(this is Err) {
		throw this.error
	} else {
		// lib code
	}
}
```

Would you be willing to accept a PR for something like this? Name TBA, fire if you have any suggestions.
Also, would you place such a function in And.kt or Factory.kt?
```kotlin
.andThenCatching {
	// lib code
}
```

**Comment by michaelbull** [comment]
```kotlin
.runCatching {
	if(it is Err) {
		throw it
	} else {
		// lib code
	}
}
```

This part of your example doesn't make sense to me. What is `it` in this context?

The current implementation of `runCatching` has no argument, therefore has no `it`:

```kotlin
public inline fun <V> runCatching(block: () -> V): Result<V, Throwable>
```

---

Generally to solve your problem I would make my own function that calls `runCatching` on the library code, rather than nesting it as per your example.

```kotlin
sealed class StepError {
    object One : DomainError()
    object Two : DomainError()
    class Vendor : DomainError(val message: String)
}

fun runAllSteps(): Result<Int, StepError> {
    return stepOne()
        .andThen(::stepTwo)
        .andThen(::callVendor)
        .mapErr(::vendorExceptionToError)
}

fun stepOne(): Result<Int, StepError.One> = TODO()

fun stepTwo(): Result<Int, StepError.Two> = TODO()

fun callVendor(): Result<Int, Throwable> = runCatching {
     // call third party library
}

fun vendorExceptionToError(throwable: Throwable) = StepError.Vendor(throwable.message)
```

**Comment by oddsund** [comment]
Sorry, updated the example. The example used the follwing call; 
```kotlin
public inline infix fun <T, V> T.runCatching(block: T.() -> V): Result<V, Throwable> {
```

So `it` was supposed to be `this`, as one would have if the call was chained.

I've already solved it (kind of) like that a few times, so I guess I'll keep going that way. Still learning, so thanks for the tip!

**Comment by michaelbull** [comment]
No worries. Generally I'm apprehensive to changes like this because we would effectively end up going through the whole library adding `xCatching` variants for every function, in order for the library to comprehensively handle the cases where you're working with code that throws instead of returning a `Result`. I'd rather keep the library more focused and encourage people to be writing their code first-and-foremost with `Result` in mind, and only using things like `runCatching` when interacting with code they can't control.
